[build]
  # Répertoire de construction
  publish = ".next"
  # Commande de build
  command = "npm run build"

[build.environment]
  # Variables d'environnement pour la construction
  NODE_VERSION = "18"

[[redirects]]
  # Redirection pour SPA (Single Page Application)
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Répertoire des fonctions serverless (si nécessaire)
  directory = "netlify/functions"

[[headers]]
  # Headers de sécurité pour les fichiers statiques
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache pour les assets statiques
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Sécurité pour les pages HTML
  for = "*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"